[build]
  base    = "techtreck-learning"
  command = "npm install && ng build --configuration production"
  publish = "dist/techtreck-learning"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

