[build]
  base    = "techtreck-learning"
  command = """
    mkdir -p src/environments &&
    echo 'export const environment = { production: true, apiUrl: "https://your.api.url" };' \
      > src/environments/environment.ts &&
    npm install &&
    ng build --configuration production
  """
  publish = "dist/techtreck-learning"

[[redirect]]
  from   = "/*"
  to     = "/index.html"
  status = 200
