name: Build and deploy Python app to Azure Web App - petruzdroba

on:
  push:
    branches:
      - main
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          cd techtreck-learning/backend
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          AZURE_DOMAIN: "https://dummy-azure-app.azurewebsites.net,https://dummy-frontend.netlify.app"
          DJANGO_ALLOWED_HOSTS: "dummy-frontend.netlify.app,localhost,dummy-azure-app.azurewebsites.net"
          DJANGO_CORS_ALLOWED_ORIGINS: "https://dummy-frontend.netlify.app"
          DJANGO_DEBUG: "False"
          DJANGO_SECRET_KEY: "dummysecretkey1234567890"
        run: |
          cd techtreck-learning/backend
          python manage.py test

      - name: Zip artifact for deployment
        run: |
          cd techtreck-learning/backend
          zip -r ../../release.zip .
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56453FF7822B4140AEAEC9EA1036DCAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0D4C0A47953B41EB936D10646C311546 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_36D4DF4A39934803842F96817592DEA7 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "petruzdroba"
          package: release.zip
          type: zip
